# 2021-10-11

## 2021-10-08 문제점 #2 계속

```bash
Assertion failed: n == 0 && "iterator out of bounds", file C:\Temp\boost_1_77_0\boost_1_77_0\boost\asio\buffers_iterator.hpp, line 434
```

해당  오류는 반드시 일어난다.

이것은 구조의 문제로 밖에 안 보인다. streambuf를 읽는 핸들러는 스레드로부터 안전하지 않은것 같다. 어떤 상황에서 일어나는지 정확하게는 모르지만 추론은 할 수 있다. 하나의 서버에서 여러가지의 클라이언트를 생성하고 몇분만 기다리면 이러한 에러가 발생하고 한번에 다 죽어버린다. 

```C++
// boost-asio-network-client/main.cpp
boost::asio::io_context context;
ban::login_client<std::string> c(context);

if (c.start("127.0.0.1", 9000, 2000))
{
    std::cout << "client main login_client started .. \n";
}

bool bQuit = false;
std::vector<bool> key(5, false);
std::vector<bool> old_key(5, false);
try
{
    while (!bQuit && c.ptr()->connected())
    {
        if (GetForegroundWindow() == GetConsoleWindow())
        {
            key[0] = GetAsyncKeyState('1') & 0x8000;
            key[1] = GetAsyncKeyState('2') & 0x8000;
            key[2] = GetAsyncKeyState('3') & 0x8000;
            key[3] = GetAsyncKeyState('4') & 0x8000;
            key[4] = GetAsyncKeyState(VK_ESCAPE) & 0x8000;
        }
		// 키보드 입력을 바탕으로 서버에 전송
        if (key[0] && !old_key[0])
        {
            c.ptr()->send("login");
        }
        if (key[1] && !old_key[1])
        {
            c.ptr()->send("enter lobby");
        }
        if (key[2] && !old_key[2])
        {
            c.ptr()->send("start matching");
        }
        if (key[3] && !old_key[3])
        {
            //c.ptr()->send("searching room");
        }
        if (key[4] && !old_key[4])
        {
            //c.ptr()->send("disconnect");
            std::cout << "disconnection key pressed\n";
            c.stop();
            bQuit = true;
        }

        for (size_t i = 0; i < key.size(); ++i)
        {
            old_key[i] = key[i];
        }
    }

}
catch (const std::exception& exception)
{
    std::cerr << exception.what() << "\n";
}
```

입력이 동시에 눌리게 된다면 async_write 부분에서 메시지가 두개가 겹치게 되고 이상한 문장이 가서 에러를 일으킬 수 있다. 이것 역시 의심.. 😑

일단 이슈로 남겨놓는다.